# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements.txt
      run: |
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Run bash script ckeck docker
      run:
        sh bin/check.sh topic:v1
    - name: Docker build image
      run:
        docker build -t topic:v1 .
    - name: Run docker image
      run:
        docker run --name topic-api -p 5000:5000 -d topic:v1
